description: MCP230xx I2C-based GPIO expander

compatible: "microchip,mcp230xx"

include: [gpio-controller.yaml, i2c-device.yaml]

properties:
  reg:
    required: true
  label:
    type: string
  "#gpio-cells":
    const: 2
  ngpios:
    type: int
    required: true
    const: 16

gpio-cells:
  - pin
  - flags
